# libnixexpr, transcribed from meson.build and its subdirectories.
{
  pkgs,
  nixMake,
  nix-util,
  nix-store,
  nix-fetchers,
}:

let
  # The parser and lexer are generated by bison and flex. The scanner is
  # told (via `generated`) that their outputs inherit the #includes of
  # parser.y and lexer.l, so it does not need to build them at evaluation
  # time.
  parserTab = pkgs.runCommand "parser-tab" { nativeBuildInputs = [ pkgs.bison ]; } ''
    mkdir $out
    bison -v -o $out/parser-tab.cc -d ${./parser.y}
  '';

  lexerTab = pkgs.runCommand "lexer-tab" { nativeBuildInputs = [ pkgs.flex ]; } ''
    mkdir $out
    flex -Cf --outfile $out/lexer-tab.cc --header-file=$out/lexer-tab.hh ${./lexer.l}
  '';
in

nixMake.mkComponent {
  name = "determinate-nix-expr";
  libName = "nixexpr";

  deps = [
    nix-util
    nix-store
    nix-fetchers
  ];

  root = ./.;

  # `builtins.wasm` is only built with WebAssembly support.
  excludeSources = pkgs.lib.optional (!nixMake.config.wasm) "primops/wasm.cc";

  includeDirs = [
    ""
    "include"
  ];

  files = nixMake.commonSupportFiles;

  embeds."eval.cc" = {
    "imported-drv-to-derivation.nix" = ./imported-drv-to-derivation.nix;
    "fetchurl.nix" = ./fetchurl.nix;
    "primops/derivation.nix" = ./primops/derivation.nix;
  };

  generated = {
    "parser-tab.hh" = {
      from = "parser.y";
      path = "${parserTab}/parser-tab.hh";
    };
    "parser-tab.cc" = {
      from = "parser.y";
      path = "${parserTab}/parser-tab.cc";
    };
    "lexer-tab.hh" = {
      from = "lexer.l";
      path = "${lexerTab}/lexer-tab.hh";
    };
    "lexer-tab.cc" = {
      from = "lexer.l";
      path = "${lexerTab}/lexer-tab.cc";
    };
  };

  configHeaders = {
    "include/nix/expr/config.hh" = {
      NIX_USE_BOEHMGC = nixMake.config.boehmgc;
    };
    "expr-config-private.hh" = {
      HAVE_PTHREAD_GETATTR_NP = 1;
      HAVE_SYSCONF = 1;
      HAVE_TOML11_4 = 1;
    };
  };

  # Build the parser without assertions and with a higher inlining
  # threshold in non-debug builds: Bison/Flex are particularly sensitive
  # to the compiler failing to inline.
  unitCxxFlags =
    let
      parserFlags = pkgs.lib.optionals (!nixMake.config.debug) [
        "-DNDEBUG"
        "--param=max-inline-insns-single=1000"
        "--param=max-inline-insns-auto=1000"
        "--param=inline-unit-growth=400"
      ];
    in
    {
      "parser-tab.cc" = parserFlags;
      "lexer-tab.cc" = parserFlags;
      "lexer-helpers.cc" = parserFlags;
    };

  extraCxxFlags = nixMake.weakVtablesFlags;

  linkFlags = [ "-Wl,--wrap=__assert_fail" ];
}
